# Generated by Django 4.2.4 on 2023-09-04 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 10, 30, 50, 532717, tzinfo=datetime.timezone.utc)),
        ),
    ]
