# Generated by Django 4.2.4 on 2023-09-04 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_alter_article_pub_date_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 11, 42, 44, 931417, tzinfo=datetime.timezone.utc)),
        ),
    ]
