# Generated by Django 4.2.4 on 2023-09-04 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 12, 33, 30, 326901, tzinfo=datetime.timezone.utc)),
        ),
    ]
